In [14]:
import torch

# **Tensor** - A tensor is a number, vector, matrix or any n-dimensial array.

In [15]:
tensor_number = torch.tensor(4.)
tensor_number
tensor_number.dtype # shows the type of tensor in this case it is 32 and number

torch.float32

In [16]:
tensor_vector = torch.tensor([12, 22, 32, 45]) # tensor vector
tensor_vector

tensor([12, 22, 32, 45])

In [17]:
tensor_matrix = torch.tensor([[12,45], [77,33], [45,65]]) # tensor matrix
tensor_matrix

tensor([[12, 45],
        [77, 33],
        [45, 65]])

In [19]:
tensor_array = torch.tensor([[[12,32], [55,66]],[[78,98],[56,22]]])
tensor_array # dimensional array

tensor([[[12, 32],
         [55, 66]],

        [[78, 98],
         [56, 22]]])

We can use **.shape** to check the length of array

In [20]:
tensor_number.shape
tensor_array.shape
tensor_vector.shape
tensor_matrix.shape

torch.Size([3, 2])

# **Tensor Opertions and Gradients**

In [30]:
a = torch.tensor(17.)
b = torch.tensor(21.)
c = torch.tensor(4., requires_grad = True) # In ML, I need derivatives a lot. Require_grad is the function

y = a*b + c # can calculate this tensor by using the floating single number
c.grad
c

tensor(4., requires_grad=True)

# **Interoperability with numpy**
Numpy is Pyhton library use to work with array.
**Matplotlib** - for visualization and plotting
**OpenCV** - for image and video processing
**Pandas** - for file I/O and data analysis

In [36]:
import numpy as np

x = np.array([[1,2],[3,3]]) # craete a array

y = torch.from_numpy(x) # convert numpy to tensor
z = y.numpy() # convert tensor to numpy

tensor([[1, 2],
        [3, 3]])

**Array vs Tensor : ** Actually arrays works with CPU and it takes time, but tensors are used by torch and it is powered with NIVEA GPU and it takes less time than CPU. 