In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)



2.0.0+cu118


# Introduction to Tensors :

In [ ]:
from torch.storage import T
scaler = torch.tensor(7)
print(f'{scaler} and {scaler.ndim} dimension.')

vector = torch.tensor([1,7])
print(f'{vector} and {vector.ndim} dimension.')

MATRIX = torch.tensor([[1,3], [3,5]])
print(f'{MATRIX} and {MATRIX.ndim} dimension.')

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]])
print(f'{TENSOR} and {TENSOR.ndim} dimension.')


# importing random numbers for tensor:

random_tensor = torch.rand(2,3)
random_tensor

# ones and zeros

ones = torch.ones(3,4) # print three by four tensor consists of only ones
zeros = torch.zeros(3,4)  # print three by four tensor consists of only zeros

zeros.dtype # show the types of data

# creating the range of tensors and tensor-like

tensor_range = torch.arange(1, 77, 2) # in latest update of pytorch we should use arange instead of range  
tensor_like = torch.zeros_like(tensor_range) # take the size of above mentioned tensor and make the same size of tensor like that

# tensor operations  

tensor_number_set = torch.tensor([1, 2, 3, 4, 5, 6])
tensor_number_set + 10 # torch.add(tensor_number_set, 10)
tensor_number_set * 10 # torch.mul(tensor_number_set, 10)
tensor_number_set - 10

#matrix multipilication. 

tensor_number_set = torch.tensor([1, 2, 3, 4, 5, 6])
torch.matmul(tensor_number_set, tensor_number_set) # torch.matmul is equal to torch.mm 

# common mistakes and two main rules: 1) innter dimension must match which means that (3,2) and (3,2) can't multiply
# because inner value should match. and (3, 2) * (2, 3), now inner values match two and two. For example :

first_set = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
second_set = torch.tensor([[7,8],
                          [9,10],
                          [11,12]])


#RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2) : bcz od inner dimension problem. To solve this, we can use,
#'Transpose' (tensor_set_name.T) which switches the axes or dimensions of the given tensor.

first_set = first_set.T 
torch.mm(first_set, second_set)

# Finding min, max, mean, sum, etc (tensor aggregation)

tensor_aggregation = torch.rand(1,10)
torch.min(tensor_aggregation)
torch.max(tensor_aggregation)
torch.mean(tensor_aggregation)
torch.sum(tensor_aggregation)

# finding the min and max value position

tensor_aggregation.argmin() # index of min value
tensor_aggregation.argmin() # index of max value

# reproducbility random _seed as the same as sklearn

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
x = torch.rand(1,9)

torch.manual_seed(RANDOM_SEED)
y = torch.rand(1,9)

x == y

# Putting tensors/models on the GPU

device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
 


7 and 0 dimension.
tensor([1, 7]) and 1 dimension.
tensor([[1, 3],
        [3, 5]]) and 2 dimension.
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) and 3 dimension.
tensor([1, 2, 3]) cpu
